import { BarChart3, CircleDollarSign, EyeOff, PackageCheck, PackageOpen, ShoppingBag } from 'lucide-react'
import { useEffect, useState } from 'react'
import { ErrorState, LoadingCard } from '../components/ui/States'
import { usePageMeta } from '../hooks/usePageMeta'
import { getAdminProducts } from '../lib/products'
import { friendlyError } from '../lib/supabase'
import type { AdminProduct } from '../types/database'

export default function AdminAnalytics() {
  usePageMeta('Аналитика | ocekyWT')
  const [products, setProducts] = useState<AdminProduct[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = async () => { setLoading(true); setError(null); try { setProducts(await getAdminProducts()) } catch (reason) { setError(friendlyError(reason, 'Не удалось загрузить аналитику.')) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const available = products.filter((product) => product.status === 'available'); const sold = products.filter((product) => product.status === 'sold'); const hidden = products.filter((product) => product.status === 'hidden')
  const sum = (items: AdminProduct[], selector: (product: AdminProduct) => number | null) => { const values = items.map(selector).filter((value): value is number => value !== null && Number.isFinite(value)); return values.length ? values.reduce((total, value) => total + value, 0) : null }
  const costRub = sum(products, (product) => product.cost_rub === null ? null : Number(product.cost_rub)); const costUsd = sum(products, (product) => product.cost_usd === null ? null : Number(product.cost_usd)); const listedValue = sum(available, (product) => Number(product.price)); const potentialProfit = sum(available, (product) => product.profit === null ? null : Number(product.profit)); const actualProfit = sum(sold, (product) => product.profit === null ? null : Number(product.profit))
  return <><div><p className="eyebrow">private metrics</p><h1 className="mt-2 text-3xl font-black">Аналитика</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Данные доступны только администратору. Прибыль считается только для позиций, где указаны себестоимость в RUB и, при необходимости, комиссия.</p></div>{loading ? <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4, 5, 6, 7, 8].map((item) => <LoadingCard key={item} className="h-32" />)}</div> : error ? <div className="mt-8"><ErrorState message={error} retry={load} /></div> : <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card icon={PackageOpen} label="Всего товаров" value={String(products.length)} /><Card icon={PackageCheck} label="Доступные" value={String(available.length)} /><Card icon={ShoppingBag} label="Проданные" value={String(sold.length)} /><Card icon={EyeOff} label="Скрытые" value={String(hidden.length)} /><Card icon={CircleDollarSign} label="Общая себестоимость, ₽" value={money(costRub)} note={costRub === null ? 'Нет данных в RUB' : 'По заполненным полям'} /><Card icon={CircleDollarSign} label="Общая себестоимость, $" value={money(costUsd)} note={costUsd === null ? 'Нет данных в USD' : 'По заполненным полям'} /><Card icon={BarChart3} label="Стоимость доступных, ₽" value={money(listedValue)} note="По публичной цене" /><Card icon={BarChart3} label="Потенциальная прибыль, ₽" value={money(potentialProfit)} note={potentialProfit === null ? 'Нет данных для расчёта' : 'По доступным товарам'} /><Card icon={CircleDollarSign} label="Фактическая прибыль, ₽" value={money(actualProfit)} note={actualProfit === null ? 'Нет данных для расчёта' : 'По проданным товарам'} /></div>}</>
}
function money(value: number | null) { return value === null ? 'Нет данных' : value.toLocaleString('ru-RU', { maximumFractionDigits: 2 }) }
function Card({ icon: Icon, label, value, note }: { icon: typeof BarChart3; label: string; value: string; note?: string }) { return <article className="panel rounded-xl p-5"><Icon className="h-5 w-5 text-ice" /><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-white">{value}</p>{note && <p className="mt-2 text-xs text-slate-500">{note}</p>}</article> }
