import { EyeOff, PackageCheck, PackageOpen, Plus, Settings2, ShoppingBag, Wallet } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ErrorState, LoadingCard } from '../components/ui/States'
import { usePageMeta } from '../hooks/usePageMeta'
import { getAdminProducts } from '../lib/products'
import { friendlyError } from '../lib/supabase'
import type { AdminProduct } from '../types/database'
import { StatusBadge } from '../components/products/StatusBadge'

export default function AdminDashboard() {
  usePageMeta('Админ-панель | ocekyWT')
  const [products, setProducts] = useState<AdminProduct[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = async () => { setLoading(true); setError(null); try { setProducts(await getAdminProducts()) } catch (reason) { setError(friendlyError(reason, 'Не удалось загрузить dashboard.')) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const available = products.filter((product) => product.status === 'available'); const sold = products.filter((product) => product.status === 'sold'); const hidden = products.filter((product) => product.status === 'hidden'); const totalAvailable = available.reduce((sum, product) => sum + Number(product.price), 0)
  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">control center</p><h1 className="mt-2 text-3xl font-black">Dashboard</h1><p className="mt-2 text-sm text-slate-400">Состояние витрины и быстрый доступ к управлению товарами.</p></div><Link to="/admin/products/new" className="btn-primary"><Plus className="h-4 w-4" />Добавить товар</Link></div>{loading ? <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <LoadingCard key={item} className="h-28" />)}</div> : error ? <div className="mt-8"><ErrorState message={error} retry={load} /></div> : <><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={PackageOpen} label="Всего товаров" value={products.length.toLocaleString('ru-RU')} /><Metric icon={PackageCheck} label="Доступно" value={available.length.toLocaleString('ru-RU')} /><Metric icon={ShoppingBag} label="Продано" value={sold.length.toLocaleString('ru-RU')} /><Metric icon={EyeOff} label="Скрыто" value={hidden.length.toLocaleString('ru-RU')} /></div><div className="mt-4 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><section className="panel rounded-xl p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Суммарная стоимость доступных</p><p className="mt-2 flex items-center gap-2 text-3xl font-black"><Wallet className="h-6 w-6 text-ice" />{totalAvailable.toLocaleString('ru-RU')} ₽</p><p className="mt-2 text-xs text-slate-500">Сумма по публичному полю цены доступных товаров.</p></section><section className="panel rounded-xl p-5"><Settings2 className="h-6 w-6 text-ice" /><h2 className="mt-3 font-bold">Быстрые действия</h2><div className="mt-4 flex flex-wrap gap-2"><Link to="/admin/products/new" className="btn-secondary text-xs">Создать товар</Link><Link to="/admin/products" className="btn-secondary text-xs">Управлять каталогом</Link><Link to="/admin/analytics" className="btn-secondary text-xs">Открыть аналитику</Link></div></section></div><section className="panel mt-6 rounded-xl p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Последние добавленные</h2><Link to="/admin/products" className="text-sm text-ice hover:text-sky-200">Все товары</Link></div>{products.length ? <div className="mt-4 divide-y divide-slate-800">{products.slice(0, 5).map((product) => <div key={product.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><Link to={`/admin/products/${product.id}/edit`} className="font-medium hover:text-ice">{product.title}</Link><p className="mt-1 text-xs text-slate-500">{new Date(product.created_at).toLocaleDateString('ru-RU')}</p></div><div className="flex items-center gap-4"><span className="text-sm font-semibold">{Number(product.price).toLocaleString('ru-RU')} {product.currency}</span><StatusBadge status={product.status} /></div></div>)}</div> : <p className="mt-4 text-sm text-slate-500">Товаров пока нет.</p>}</section></>}</>
}
function Metric({ icon: Icon, label, value }: { icon: typeof PackageOpen; label: string; value: string }) { return <article className="panel rounded-xl p-5"><Icon className="h-5 w-5 text-ice" /><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></article> }
